import './models/initialize'
import './controls/route'
import './controls/keyboard'
import './controls/navigation'
import miniframe from './views/miniframe'
import './views/scale'
import './views/slide'
import './views/progressbar'
